In [1]:
import numpy as np
import pandas as py

In [2]:
#create virtual environment and have these libraries
#python -m

#numpy
#pandas
#matplotlib
#seaborn
#scikitlearn
#tensorflow
#pytorch
#keras

#JAX library (numpy)
#Polar or Dask libraray (pandas)

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
a.shape

(3,)

In [5]:
b = np.arange(1, 60, 10)
print(b)
b.shape

[ 1 11 21 31 41 51]


(6,)

In [6]:
b = np.reshape(b, (2, 3))
print(b)
b.shape

[[ 1 11 21]
 [31 41 51]]


(2, 3)

In [7]:
b = np.reshape(b, (-1, 1))
print(b)
b.shape

[[ 1]
 [11]
 [21]
 [31]
 [41]
 [51]]


(6, 1)

In [8]:
c = np.arange(5, 95, 5)
print(c)
print(c.shape)

c = np.reshape(c, (-1,1))
print(c)
c.shape

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90]
(18,)
[[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]
 [50]
 [55]
 [60]
 [65]
 [70]
 [75]
 [80]
 [85]
 [90]]


(18, 1)

In [9]:
d = np.arange(48).reshape(2, 2, 3, 4)
print(d)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


In [10]:
#dot product 4 methods

#indexing and slicing
a1 = np.arange(10)
print(a1)
print()
a2 = np.arange(12).reshape(3, 4)
print(a2)
print()
a3 = np.arange(8).reshape(2, 2, 2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [11]:
a1[-1:-8:-2]

array([9, 7, 5, 3])

In [12]:
a2[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
a2[1:, 0::3]

array([[ 4,  7],
       [ 8, 11]])

In [14]:
a3[1:,1:,0:]

array([[[6, 7]]])

In [15]:
a3[1, 1]

array([6, 7])

In [16]:
a4 = np.arange(27).reshape(3, 3, 3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
a4[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [18]:
k = np.random.randint(1, 100, 15).reshape(3, 5)
print(k)
print(k.shape)
k[k > 40]

[[53 66 95 44 91]
 [ 2 61 67 79  5]
 [42 75 63 15 63]]
(3, 5)


array([53, 66, 95, 44, 91, 61, 67, 79, 42, 75, 63, 63])

In [19]:
#if condition match then true else false 

condition = k > 40
newk = np.array(condition, dtype = bool)
print(newk)

[[ True  True  True  True  True]
 [False  True  True  True False]
 [ True  True  True False  True]]
